// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { conduitController16Artifact } from "./types/ConduitController16";

export const getOrDeployConduitController16 = defineDeployer(conduitController16Artifact, config);
