// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { eRC1155TokenArtifact } from "./types/ERC1155Token";

export const getOrDeployERC1155Token = defineDeployer(eRC1155TokenArtifact, config);
