// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { eRC20TokenArtifact } from "./types/ERC20Token";

export const getOrDeployERC20Token = defineDeployer(eRC20TokenArtifact, config);
