// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { eRC721TokenArtifact } from "./types/ERC721Token";

export const getOrDeployERC721Token = defineDeployer(eRC721TokenArtifact, config);
