// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineRegister, defineReset } from "deployoor";
import config from "../deployoor.config";

export { getOrDeployConduitController16 } from "./ConduitController16";
export { getOrDeployERC1155Token } from "./ERC1155Token";
export { getOrDeployERC20Token } from "./ERC20Token";
export { getOrDeployERC721Token } from "./ERC721Token";
export { getOrDeployPinkwhale } from "./Pinkwhale";
export { getOrDeploySeaport16 } from "./Seaport16";

// Record a contract you did not deploy (e.g. USDC), or forget recorded deployments —
// both config-bound and scoped to the client's chain, like the generated deployers.
export const register = defineRegister(config);
export const reset = defineReset(config);
