// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { pinkwhaleArtifact } from "./types/Pinkwhale";

export const getOrDeployPinkwhale = defineDeployer(pinkwhaleArtifact, config);
