// AUTO-GENERATED by deployoor. Do not edit by hand.
import { defineDeployer } from "deployoor";
import config from "../deployoor.config";
import { seaport16Artifact } from "./types/Seaport16";

export const getOrDeploySeaport16 = defineDeployer(seaport16Artifact, config);
